-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS departments.department;

CREATE TABLE IF NOT EXISTS departments.department
(
    dept_no character varying COLLATE pg_catalog."default" NOT NULL,
    dept_name character varying COLLATE pg_catalog."default",
    CONSTRAINT department_pkey PRIMARY KEY (dept_no)
);

DROP TABLE IF EXISTS departments.department_employees;

CREATE TABLE IF NOT EXISTS departments.department_employees
(
    emp_no character varying COLLATE pg_catalog."default" NOT NULL,
    dept_no character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "department employees _pkey" PRIMARY KEY (emp_no, dept_no)
);

DROP TABLE IF EXISTS departments.department_manager;

CREATE TABLE IF NOT EXISTS departments.department_manager
(
    dept_no character varying COLLATE pg_catalog."default",
    emp_no character varying COLLATE pg_catalog."default"
);

DROP TABLE IF EXISTS employees.employee;

CREATE TABLE IF NOT EXISTS employees.employee
(
    emp_no character varying COLLATE pg_catalog."default" NOT NULL,
    emp_title_id character varying COLLATE pg_catalog."default",
    birth_date character varying COLLATE pg_catalog."default",
    first_name character varying COLLATE pg_catalog."default",
    last_name character varying COLLATE pg_catalog."default",
    sex character varying COLLATE pg_catalog."default",
    hire_date character varying COLLATE pg_catalog."default",
    CONSTRAINT employee_pkey PRIMARY KEY (emp_no)
);

DROP TABLE IF EXISTS salary.salaries;

CREATE TABLE IF NOT EXISTS salary.salaries
(
    emp_no character varying COLLATE pg_catalog."default" NOT NULL,
    salary character varying COLLATE pg_catalog."default",
    CONSTRAINT salaries_pkey PRIMARY KEY (emp_no)
);

DROP TABLE IF EXISTS title.titles;

CREATE TABLE IF NOT EXISTS title.titles
(
    title_id character varying COLLATE pg_catalog."default" NOT NULL,
    title character varying COLLATE pg_catalog."default",
    CONSTRAINT titles_pkey PRIMARY KEY (title_id)
);
END;